autoinvento/suppliers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Email



class AddSupplier(FlaskForm):
    name = StringField('Supplier Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    contact = StringField('Address', validators=[DataRequired(Length(min=2, max=120))])
    phone_number = StringField('Phone No')
    submit = SubmitField('Add Supplier')

autoinvento/suppliers/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template, request, jsonify
from flask_login import current_user, login_required
from autoinvento.suppliers.forms import AddSupplier
from autoinvento.models import Supplier, InventoryItem
from autoinvento import db
from sqlalchemy import func


supplier = Blueprint('supplier', __name__)


@supplier.route('/suppliers/add', methods=['GET', 'POST'])
@login_required
def add_suppliers():
    form = AddSupplier()
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    if form.validate_on_submit():
        supplier = Supplier(name=form.name.data, email=form.email.data, contact=form.contact.data)
        db.session.add(supplier)
        db.session.commit()
        flash('Supplier successfully inserted!', 'success')
        return redirect(url_for('supplier.suppliers'))
    return render_template('add_suppliers.html', title='Add Suppliers', legend='Add Supplier', form=form)


@supplier.route('/supplier/view', methods=['GET', 'POST'])
@login_required
def suppliers():
    suppliers = Supplier.query.all()
    return render_template('suppliers.html', title='Suppliers', suppliers=suppliers)


@supplier.route('/suppliers/view/<int:supplier_id>', methods=['GET', 'POST'])
@login_required
def view_supplier(supplier_id):
    supplier = Supplier.query.get_or_404(supplier_id)
    supplier_products = InventoryItem.query.filter_by(supplier_id=supplier.id).all()
    return render_template('view_supplier.html', title=supplier.name, supplier=supplier, supplier_products=supplier_products)



@supplier.route('/suppliers/<int:supplier_id>/update', methods=['GET', 'POST'])
@login_required
def update_supplier(supplier_id):
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    
    supplier = Supplier.query.get_or_404(supplier_id)
    form = AddSupplier()
    if form.validate_on_submit():
        supplier.name = form.name.data
        supplier.email = form.email.data
        supplier.contact = form.contact.data
        supplier.phone_number = form.phone_number.data
        db.session.commit()
        flash('Supplier Information updated successfully!', 'success')
        return redirect(url_for('supplier.suppliers'))
    elif request.method == 'GET':
        form.name.data = supplier.name
        form.email.data = supplier.email
        form.contact.data = supplier.contact
        form.phone_number.data = supplier.phone_number
    return render_template('add_suppliers.html', title=f'Update {supplier.name}', legend='Update Supplier', supplier=supplier, form=form)


@supplier.route('/suppliers/<int:supplier_id>/delete', methods=['POST'])
@login_required
def delete_supplier(supplier_id):
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    supplier = Supplier.query.get_or_404(supplier_id)
    db.session.delete(supplier)
    db.session.commit()
    flash('Supplier deleted successfully!', 'success')
    return redirect(url_for('supplier.suppliers', supplier=supplier))


@supplier.route('/api/inventory-data')
@login_required
def get_inventory_supplier_data():
    # Query the database to get the quantity of items supplied by each supplier
    supplier_data = (
        Supplier.query
        .join(InventoryItem, Supplier.id == InventoryItem.supplier_id)
        .with_entities(Supplier.name, func.sum(InventoryItem.quantity).label('total_quantity'))
        .group_by(Supplier.name)
        .all()
    )

    # Convert the data to a format suitable for returning as JSON
    data_for_chart = [{'supplier': item[0], 'total_quantity': item[1]} for item in supplier_data]

    return jsonify(data_for_chart)

autoinvento/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app, jsonify
from autoinvento.users.forms import CreateMechanicForm, LoginForm, UpdateAccountForm, RequestForm, UpdateMechanicForm, OwnerActionForm, RequestResetForm, ResetPasswordForm
from autoinvento.users.utils import save_picture, send_reset_email
from autoinvento import db, bcrypt, mail
from flask_mail import Message
from autoinvento.models import Mechanics, Supplier, InventoryItem, InventoryRequest
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import func


users = Blueprint('users', __name__)


@users.route('/create_mechanic', methods=['GET', 'POST'])
def create_mechanic():
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    form = CreateMechanicForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        is_superuser = form.is_superuser.data
        user = Mechanics(
            username=form.mechanic.data,
            email=form.email.data,
            password=hashed_password,
            is_superuser = is_superuser
        )
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.mechanic.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('create_mechanic.html', title='Create Mechanic', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if current_user.is_superuser:
            return redirect(url_for('users.owner_dashboard'))
        else:
            return redirect(url_for('users.mechanic_dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Mechanics.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if user.is_superuser:
                return redirect(next_page) if next_page else redirect(url_for('users.owner_dashboard'))
            else:
                return redirect(next_page) if next_page else redirect(url_for('users.mechanic_dashboard'))
        else:
            flash('Login Unsuccessful, check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='images/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/owner/dashboard', methods=(['GET', 'POST']))
@login_required
def owner_dashboard():
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    total_suppliers = Supplier.query.count()
    mechanics= Mechanics.query.filter_by(is_superuser=False).count()
    total_products = InventoryItem.query.count()
    low_stock = InventoryItem.query.filter(InventoryItem.quantity <= InventoryItem.low_stock_threshold).all()
    total_low_stock = len(low_stock)
    stock_out =InventoryItem.query.filter(InventoryItem.quantity == 0).all()
    total_stock_out = len(stock_out)
    return render_template('owner_dashboard.html', title='Owner DashBoard',
                           total_suppliers=total_suppliers,
                           mechanics=mechanics,
                           total_products=total_products,
                           total_low_stock=total_low_stock,
                           total_stock_out=total_stock_out,
                          #supply_chart_data=supply_chart_data
                           )



@users.route('/mechanic/dashboard', methods=['GET', 'POST'])
@login_required
def mechanic_dashboard():
    if not current_user.is_authenticated or current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.owner_dashboard'))
    total_suppliers = Supplier.query.count()
    mechanics = Mechanics.query.filter_by(is_superuser=False).count()
    total_products = InventoryItem.query.count()
    low_stock = InventoryItem.query.filter(InventoryItem.quantity <= InventoryItem.low_stock_threshold).all()
    total_low_stock = len(low_stock)
    stock_out =InventoryItem.query.filter(InventoryItem.quantity == 0).all()
    total_stock_out = len(stock_out)
    return render_template(
                            'mechanic_dashboard.html',
                            title='Mechanic Dashboard',
                            total_suppliers=total_suppliers,
                            mechanics=mechanics,
                           total_products=total_products,
                           total_low_stock=total_low_stock,
                           total_stock_out=total_stock_out
                        )


@users.route('/owner/dashboard/mechanics', methods=(['GET']))
@login_required
def mechanics():
    users = Mechanics.query.filter_by(is_superuser = False).all() 
    return render_template('mechanics.html', title='Mechanics', users=users)


@users.route('/mechanic/<int:mechanic_id>/update', methods=(['GET', 'POST']))
@login_required
def update_mechanic(mechanic_id):
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    mechanic = Mechanics.query.get_or_404(mechanic_id)
    form = UpdateMechanicForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            mechanic.image_file = picture_file
        mechanic.username = form.username.data
        mechanic.email = form.email.data
        db.session.commit()
        flash('Mechanic updated successfully!', 'success')
        return redirect(url_for('users.mechanics'))
    elif request.method == 'GET':
        form.username.data = mechanic.username
        form.email.data = mechanic.email
    image_file = url_for('static', filename='images/' + mechanic.image_file)
    return render_template('update_mechanic.html', title=f"Update {mechanic.username}", mechanic=mechanic, image_file=image_file, form=form)



@users.route('/mechanic/<int:mechanic_id>/delete', methods=['POST'])
@login_required
def delete_mechanic(mechanic_id):
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    mechanic = Mechanics.query.get_or_404(mechanic_id)
    db.session.delete(mechanic)
    db.session.commit()
    flash('Mechanic successfully deleted!', 'success')
    return redirect(url_for('users.mechanics'))



@users.route('/submit_request', methods=['GET', 'POST'])
@login_required
def submit_request():
    form = RequestForm()
    form.item_id.choices = [(item.id, item.name) for item in InventoryItem.query.all()]
    
    try:
        if form.validate_on_submit():
            quantity_requested = form.quantity_requested.data
            item_id = form.item_id.data

            # Check if quantity requested is greater than 0
            if quantity_requested <= 0:
                flash('Quantity requested must be greater than 0.', 'danger')
                return render_template('users.submit_request.html', title='Submit Request', form=form)

            # Check if quantity requested is available in InventoryItem
            item = InventoryItem.query.get(item_id)
            if item.quantity < quantity_requested:
                flash(f'Requested quantity ({quantity_requested}) exceeds available stock ({item.quantity}).', 'danger')
                return render_template('submit_request.html', title='Submit Request', form=form)

            # Create a new request using form data
            requests = InventoryRequest(
                item_id=item_id,
                quantity_requested=quantity_requested,
                mechanic_id=current_user.id,
                status='pending'
            )
            db.session.add(requests)
            db.session.commit()
            
            # Notify the owner via email
            owner_email = 'muchiskino@gmail.com' 
            message = Message('New Request', sender=current_app.config['MAIL_DEFAULT_SENDER'], recipients=[owner_email])
            message.body = f'A new request has been submitted by {current_user.username}. Please review it.'
            mail.send(message)

            flash('Request submitted successfully!', 'success')
            return redirect(url_for('users.submit_request'))

    except Exception as e:
        flash(f'An error occurred: {str(e)}', 'danger')

    return render_template('submit_request.html', title='Submit Request', form=form)



""" MECHANIC REQUEST ROUTES """

@users.route('/view_requests', methods=['GET'])
@login_required

autoinvento/templates/account.html
{% extends "base.html" %} {% block content %}
<style>
  /* Custom CSS for centering content and extending the page */
  body {
    background-color: rgba(34, 14, 91);
    justify-content: center;
    align-items: center;
    background-image: linear-gradient(
        rgba(34, 14, 91, 0.1),
        rgba(34, 14, 91, 0.5)
      ),
      url("{{ url_for('static', filename='images/mechanic_repair.webp') }}");
    background-size: cover;
    background-repeat: no-repeat;
  }
  .container_account {
    min-height: 100vh;
    margin: auto;
    max-width: 100%;
    width: 600px;
    box-sizing: border-box; /* Include padding in width calculation */
    overflow-x: hidden; /* Hide horizontal overflow */
  }
  .content-section {
    padding: 30px;
    margin: 10px;
    gap: 20px;
  }
</style>

<div class="container_account">
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}" />
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Account Info</legend>
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          <!-- Printing feedback messages incase of invalid input -->
          {% if form.username.errors %} {{ form.username(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          <!-- Printing feedback messages incase of invalid input -->
          {% if form.email.errors %} {{ form.email(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.email(class="form-control form-control-lg") }} {%
          endif %}
        </div>
        <div class="form-group">
          {{ form.picture.label() }} {{ form.picture(class="form-control-file")
          }} {% if form.picture.errors %} {% for error in form.picture.errors %}
          <span class="text-danger">{{ error }}</span><br />
          {% endfor %} {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
</div>
{% endblock content %}

autoinvento/templates/mechanics.html
{% extends 'base.html' %} {% block content %}
<style>
  /* Custom CSS for centering content and extending the page */
  body {
    background-image: linear-gradient(
        rgba(34, 14, 91, 0.2),
        rgba(34, 14, 91, 0.3)
      ),
      url("{{ url_for('static', filename='images/auto-image.jpg') }}");
    background-size: cover;
    background-position: center;
  }
</style>
<h2 style="color: aliceblue">Manage Mechanics</h2>
<div class="container background">
  <div class="col-md-2 float-right">
    <div class="card p-2">
      <a
        class="btn btn-sm btn-secondary"
        href="{{ url_for('users.create_mechanic') }}"
        >Add Mechanic</a
      >
    </div>
  </div>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Mechanic</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.username }}</td>
          <td>{{ user.email }}</td>
          <td>
            <div class="dropdown">
              <button
                class="btn btn-info dropdown-toggle"
                type="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Actions
              </button>
              <ul class="dropdown-menu">
                <li>
                  <a
                    href="{{ url_for('users.update_mechanic', mechanic_id=user.id) }}"
                  >
                    <button class="btn btn-secondary btn-sm">Update</button>
                  </a>
                </li>
                <li>
                  <button
                    type="button"
                    class="btn btn-danger btn-sm"
                    data-bs-toggle="modal"
                    data-bs-target="#deleteModal{{ user.id }}"
                  >
                    Delete
                  </button>
                </li>
              </ul>
            </div>
            <!-- Modal -->
            <div
              class="modal fade"
              id="deleteModal{{ user.id }}"
              tabindex="-1"
              aria-labelledby="deleteModalLabel{{ user.id }}"
              aria-hidden="true"
            >
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h3
                      class="modal-title fs-5"
                      id="deleteModalLabel{{ user.id }}"
                    >
                      Delete Mechanic?
                    </h3>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    ></button>
                  </div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary btn-sm mb-4"
                      data-bs-dismiss="modal"
                    >
                      Close
                    </button>
                    <form
                      action="{{ url_for('users.delete_mechanic', mechanic_id=user.id) }}"
                      method="POST"
                    >
                      <input
                        type="submit"
                        class="btn btn-danger btn-sm"
                        value="Delete"
                      />
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- Pagination links (if you're using Flask's pagination) -->
  {{ users.links }}
</div>

{% endblock content %}

autoinvento/templates/owner_dashboard.html
{% extends 'base.html' %} {% block content %}
  
  <!-- Container for Dashboard Content -->
  <div class="container mt-4">
    <h1 class="mb-4"> Welcome {{ current_user.username }}</h1>
    <div class="row dashboard">
      <!-- Dashboard Metrics -->
      <div class="col-md-3">
        <div class="card">
          <div class="card-body">
            <div class="float-right">
              <a href="{{ url_for('inventory.view_inventories') }}"
                ><i class="bi bi-arrow-up-right" style="font-size:large"></i
              ></a>
            </div>
            <div class="float-left mr-4 mt-1">
              <i class="bi bi-box2" style="font-size:large"></i>
            </div>
            <h5 class="card-title" style="font-size:large">Total Products</h5>
            <p class="card-text" style="color:green; font-size:large">{{ total_products }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <div class="card-body">
            <div class="float-right">
              <a href="{{ url_for('inventory.low_inventory') }}"
                ><i class="bi bi-arrow-up-right" style="font-size:large"></i
              ></a>
            </div>
            <div class="float-left mr-4 mt-1">
              <i class="bi bi-box2" style="font-size:large"></i>
            </div>
            <h5 class="card-title" style="color:goldenrod; font-size:large">Low Stock</h5>
            <p class="card-text" style="font-size:large">{{ total_low_stock }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <div class="card-body">
            <div class="float-right">
              <a href="{{ url_for('inventory.finished_inventory') }}"
                ><i class="bi bi-arrow-up-right" style="font-size:large"></i
              ></a>
            </div>
            <div class="float-left mr-4 mt-1">
              <i class="bi bi-box2" style="font-size:large"></i>
            </div>
            <h5 class="card-title" style="color:red; font-size:large">Out of Stock</h5>
            <p class="card-text" style="color:red; font-size:large">{{ total_stock_out }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <div class="card-body">
            <div class="float-right">
              <a href="{{ url_for('supplier.suppliers') }}"
                ><i class="bi bi-arrow-up-right" style="font-size:large"></i
              ></a>
            </div>
            <div class="float-left mr-4 mt-1">
              <i class="bi bi-view-list" style="font-size:large"></i>
            </div>
            <h5 class="card-title" style="color: rgb(124, 9, 47); font-size:large">Suppliers</h5>
            <p class="card-text" style="color: rgb(124, 9, 47); font-size:large">{{ total_suppliers }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 mt-4">
        <div class="card">
          <div class="card-body">
            <div class="float-right">
              <a href="{{ url_for('users.mechanics') }}"
                ><i class="bi bi-arrow-up-right" style="font-size:large"></i
              ></a>
            </div>
            <div class="float-left mr-4 mt-1">
              <i class="bi bi-person-fill-gear" style="font-size:large"></i>
            </div>
            <h5 class="card-title" style="color:blueviolet; font-size:large">Mechanics</h5>
            <p class="card-text" style="font-size:large">{{ mechanics }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 mt-4">
        <div class="card">
          <div class="card-body ml-5">
            <a class="btn btn-primary" style="font-size:medium" href="{{ url_for('inventory.add_inventory') }}"
              >Add Inventory</a
            >
          </div>
        </div>
      </div>
      <div class="col-md-3 mt-4">
        <div class="card">
          <div class="card-body ml-5">
            <a class="btn btn-primary" style="font-size:medium" href="{{ url_for('users.create_mechanic') }}"
              >Add Mechanics</a
            >
          </div>
        </div>
      </div>
      <div class="col-md-3 mt-4">
        <div class="card">
          <div class="card-body ml-5">
            <a class="btn btn-primary" style="font-size:medium" href="{{ url_for('supplier.add_suppliers') }}"
              >Add Suppliers</a
            >
          </div>
        </div>
      </div>
    </div>

    <!-- Chartjs library integration -->
    <div class="container">
      <div class="row mt-4">
        <div class="col-md-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Inventory Usage by Mechanics</h5>
              <div>
                <canvas id="myChart" height="130"></canvas>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Supplier Trends</h5>
            <div>
              <div>
                <canvas id="supplyChart" height="130"></canvas>
            </dv>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
  <script src="{{ url_for('static', filename='js/chart.js') }}"></script>
{% endblock content %}

autoinvento/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    <!-- Printing feedback messages incase of invalid input -->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>    
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

autoinvento/templates/view_requests.html
{% extends "base.html" %}

{% block content %}
    <h3 class="mt-4">My Requests</h3>
    <div class="container mt-2 background mt-4">
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Quantity</th>
            <th>Status</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
            {% for request in requests %}
        <tr>
            <td>{{ request.name }}</td>
            <td>{{ request.quantity_requested }}</td>
            <td>{{ request.status }}</td>
            <td>{{ request.request_timestamp }} </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}

autoinvento/templates/view_supplier.html
{% extends "base.html" %}

{% block content %}
    <div class="invoice-container">
        <div class="invoice-info">
            <div class="invoice-details">
                <h3>Supplier Details</h3>
                <div class="billing-info mt-4">
                    <div>
                        <p><strong>Name:</strong> {{ supplier.name }}</p>
                        <p><strong>Email:</strong> {{ supplier.email }}</p>
                    </div>
                    <div>
                        <p><strong>Phone:</strong> {{ supplier.phone_number }}</p>
                        <p><strong>Address:</strong> {{ supplier.contact }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="invoice-table">
            <h4>Supplier Products</h4>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Category</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in supplier_products %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.category }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="invoice-total">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                Delete Supplier
            </button>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Supplier?</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-sm mb-4" data-bs-dismiss="modal">Close</button>
            <form action="{{ url_for('supplier.delete_supplier', supplier_id=supplier.id) }}" method="POST">
                <input class="btn btn-danger btn-sm" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

   