autostock/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify
from autostock.users.forms import CreateMechanicForm, LoginForm, UpdateAccountForm, RequestForm, UpdateMechanicForm, OwnerActionForm
from autostock.users.utils import save_picture
from autostock import db, bcrypt
#from flask_mail import Message
from sqlalchemy import func
from autostock.models import Mechanics, Supplier, InventoryItem, InventoryRequest
from flask_login import login_user, current_user, logout_user, login_required


users = Blueprint('users', __name__)


@users.route('/create_mechanic', methods=['GET', 'POST'])
def create_mechanic():
    #if not current_user.is_authenticated or not current_user.is_superuser:
        #flash('You are not authorized to access this page.', 'danger')
        #return redirect(url_for('users.mechanic_dashboard'))
    form = CreateMechanicForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        is_superuser = form.is_superuser.data
        user = Mechanics(
            username=form.mechanic.data,
            email=form.email.data,
            password=hashed_password,
            is_superuser = is_superuser
        )
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.mechanic.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('create_mechanic.html', title='Create Mechanic', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if current_user.is_superuser:
            return redirect(url_for('users.owner_dashboard'))
        else:
            return redirect(url_for('users.mechanic_dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Mechanics.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if user.is_superuser:
                return redirect(next_page) if next_page else redirect(url_for('users.owner_dashboard'))
            else:
                return redirect(next_page) if next_page else redirect(url_for('users.mechanic_dashboard'))
        else:
            flash('Login Unsuccessful, check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='images/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/owner/dashboard', methods=(['GET', 'POST']))
@login_required
def owner_dashboard():
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    total_suppliers = Supplier.query.count()
    mechanics= Mechanics.query.filter_by(is_superuser=False).count()
    total_products = InventoryItem.query.count()
    low_stock = InventoryItem.query.filter(InventoryItem.quantity <= InventoryItem.low_stock_threshold).all()
    total_low_stock = len(low_stock)
    stock_out =InventoryItem.query.filter(InventoryItem.quantity == 0).all()
    total_stock_out = len(stock_out)
    return render_template('owner_dashboard.html', title='Owner DashBoard',
                           total_suppliers=total_suppliers,
                           mechanics=mechanics,
                           total_products=total_products,
                           total_low_stock=total_low_stock,
                           total_stock_out=total_stock_out,
                          #supply_chart_data=supply_chart_data
                           )



@users.route('/mechanic/dashboard', methods=['GET', 'POST'])
@login_required
def mechanic_dashboard():
    if not current_user.is_authenticated or current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.owner_dashboard'))
    total_suppliers = Supplier.query.count()
    mechanics = Mechanics.query.filter_by(is_superuser=False).count()
    total_products = InventoryItem.query.count()
    low_stock = InventoryItem.query.filter(InventoryItem.quantity <= InventoryItem.low_stock_threshold).all()
    total_low_stock = len(low_stock)
    stock_out =InventoryItem.query.filter(InventoryItem.quantity == 0).all()
    total_stock_out = len(stock_out)
    return render_template(
                            'mechanic_dashboard.html',
                            title='Mechanic Dashboard',
                            total_suppliers=total_suppliers,
                            mechanics=mechanics,
                           total_products=total_products,
                           total_low_stock=total_low_stock,
                           total_stock_out=total_stock_out
                        )


@users.route('/owner/dashboard/mechanics', methods=(['GET']))
@login_required
def mechanics():
    users = Mechanics.query.filter_by(is_superuser = False).all() 
    return render_template('mechanics.html', title='Mechanics', users=users)


@users.route('/mechanic/<int:mechanic_id>/update', methods=(['GET', 'POST']))
@login_required
def update_mechanic(mechanic_id):
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    mechanic = Mechanics.query.get_or_404(mechanic_id)
    form = UpdateMechanicForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            mechanic.image_file = picture_file
        mechanic.username = form.username.data
        mechanic.email = form.email.data
        db.session.commit()
        flash('Mechanic updated successfully!', 'success')
        return redirect(url_for('users.mechanics'))
    elif request.method == 'GET':
        form.username.data = mechanic.username
        form.email.data = mechanic.email
    image_file = url_for('static', filename='images/' + mechanic.image_file)
    return render_template('udpate_mechanic.html', title=f"Update {mechanic.username}", mechanic=mechanic, image_file=image_file, form=form)



@users.route('/mechanic/<int:mechanic_id>/delete', methods=['POST'])
@login_required
def delete_mechanic(mechanic_id):
    if not current_user.is_authenticated or not current_user.is_superuser:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('users.mechanic_dashboard'))
    mechanic = Mechanics.query.get_or_404(mechanic_id)
    db.session.delete(mechanic)
    db.session.commit()
    flash('Mechanic successfully deleted!', 'success')
    return redirect(url_for('users.mechanics'))



@users.route('/submit_request', methods=['GET', 'POST'])
@login_required
def submit_request():
    form = RequestForm()
    form.item_id.choices = [(item.id, item.name) for item in InventoryItem.query.all()]
    
    try:
        if form.validate_on_submit():
            quantity_requested = form.quantity_requested.data
            item_id = form.item_id.data

            # Check if quantity requested is greater than 0
            if quantity_requested <= 0:
                flash('Quantity requested must be greater than 0.', 'danger')
                return render_template('users.submit_request.html', title='Submit Request', form=form)

            # Check if quantity requested is available in InventoryItem
            item = InventoryItem.query.get(item_id)
            if item.quantity < quantity_requested:
                flash(f'Requested quantity ({quantity_requested}) exceeds available stock ({item.quantity}).', 'danger')
                return render_template('submit_request.html', title='Submit Request', form=form)

            # Create a new request using form data
            requests = InventoryRequest(
                item_id=item_id,
                quantity_requested=quantity_requested,
                mechanic_id=current_user.id,
                status='pending'
            )
            db.session.add(requests)
            db.session.commit()
            
            # Notify the owner via email
            owner_email = 'muchiskino@gmail.com' 
            #message = Message('New Request', sender=current_app.config['MAIL_DEFAULT_SENDER'], recipients=[owner_email])
            #message.body = f'A new request has been submitted by {current_user.username}. Please review it.'
            #mail.send(message)

            flash('Request submitted successfully!', 'success')
            return redirect(url_for('users.submit_request'))

    except Exception as e:
        flash(f'An error occurred: {str(e)}', 'danger')

    return render_template('submit_request.html', title='Submit Request', form=form)


@users.route('/api/inventory-data')
def get_inventory_supplier_data():
    # Query the database to get the quantity of items supplied by each supplier
    supplier_data = (

autostock/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    {% if title %}
        <title>AutoSotck | {{ title }}</title>
    {% else %}
        <title>AutoStock</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">AutoStock</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Home</a>
                {% if current_user.is_authenticated %}
                  {% if not current_user.is_superuser %}
                    <a class="nav-item nav-link" href="{{ url_for('users.mechanic_dashboard') }}">Mechanic Dashboard</a>
                  {% endif %}
                {% endif %}
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  {% if current_user.is_superuser %}
                    <a class="nav-item nav-link" href="{{ url_for('users.owner_dashboard') }}">Owner Dashboard<a></a>
                    <a class="nav-item nav-link" href="{{ url_for('users.manage_requests') }}">Manage Requests</a>
                  {% endif %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container sec">
        <div class="row">
          <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
        </div>
      </main>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </body>
</html>

autostock/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to AutoStock</h1>
    <h4>The auto-repair inventory management app</h4>
{% endblock content %}